# Generated by Django 5.2.16 on 2026-09-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="sections",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                to="academics.classsection",
                verbose_name="الشعب الدراسية المسجلة",
            ),
        ),
    ]
