# Generated by Django 5.1.4 on 2026-09-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="study_shift",
            field=models.CharField(
                choices=[("MORNING", "صباحي"), ("EVENING", "مسائي")],
                default="MORNING",
                max_length=10,
                verbose_name="نوع الدراسة (صباحي/مسائي)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "مدير النظام"),
                    ("INSTITUTION_ADMIN", "مدير المؤسسة"),
                    ("TEACHER", "معلم / مشرف"),
                    ("STUDENT", "طالب"),
                ],
                default="SUPER_ADMIN",
                max_length=20,
                verbose_name="الدور",
            ),
        ),
    ]
