# Generated by Django 5.1.4 on 2026-09-27 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_course_code_alter_course_unique_together"),
        ("accounts", "0003_studentprofile_study_shift_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="academics.department",
                verbose_name="القسم الأكاديمي",
            ),
        ),
    ]
