# Generated by Django 5.2.16 on 2026-07-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="العام الدراسي")),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                ("is_active", models.BooleanField(default=False, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "العام الدراسي",
                "verbose_name_plural": "الأعوام الدراسية",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القسم")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رمز القسم"
                    ),
                ),
            ],
            options={
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم المؤسسة")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institutions/",
                        verbose_name="الشعار",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "allowed_wifi_ssid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="اسم شبكة الـ WiFi المسموحة (SSID)",
                    ),
                ),
                (
                    "allowed_wifi_bssid",
                    models.CharField(
                        blank=True,
                        help_text="عناوين MAC لنقاط الاتصال مفرقة بفاصلة (مثال: 00:0a:95:9d:68:16)",
                        max_length=255,
                        null=True,
                        verbose_name="BSSID مسموح",
                    ),
                ),
                (
                    "allowed_ip_subnet",
                    models.CharField(
                        blank=True,
                        help_text="مثال: 192.168.4.0/24 أو 10.0.0.0/16",
                        max_length=50,
                        null=True,
                        verbose_name="نطاق الـ IP الداخلي المسموح (Subnet)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="خط الطول",
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="نطاق السماح الجغرافي بالمتر",
                        verbose_name="قطر النطاق الجغرافي",
                    ),
                ),
            ],
            options={
                "verbose_name": "المؤسسة التعليمية",
                "verbose_name_plural": "المؤسسات التعليمية",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم المادة")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز المادة"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="academics.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "المادة الدراسية",
                "verbose_name_plural": "المواد الدراسية",
            },
        ),
        migrations.CreateModel(
            name="ClassSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="اسم الشعبة/الفصل"),
                ),
                ("level", models.CharField(max_length=50, verbose_name="المستوى/الصف")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="academics.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "الفصل الدراسي/الشعبة",
                "verbose_name_plural": "الفصول الدراسية/الشعب",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="academics.institution",
                verbose_name="المؤسسة",
            ),
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="الفصل الدراسي")),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                ("is_active", models.BooleanField(default=False, verbose_name="نشط")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academics.academicyear",
                        verbose_name="العام الدراسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "الفصل الدراسي",
                "verbose_name_plural": "الفصول الدراسية",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "السبت"),
                            (1, "الأحد"),
                            (2, "الإثنين"),
                            (3, "الثلاثاء"),
                            (4, "الأربعاء"),
                            (5, "الخميس"),
                            (6, "الجمعة"),
                        ],
                        verbose_name="اليوم",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="وقت البدء")),
                ("end_time", models.TimeField(verbose_name="وقت الانتهاء")),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="القاعة/الغرفة",
                    ),
                ),
                (
                    "class_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academics.classsection",
                        verbose_name="الشعبة",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academics.course",
                        verbose_name="المادة",
                    ),
                ),
            ],
            options={
                "verbose_name": "الحصة / المحاضرة",
                "verbose_name_plural": "الحصص / المحاضرات",
            },
        ),
    ]
