# Generated by Django 5.1.4 on 2026-09-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_classsection_shift_session_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, verbose_name="رمز المادة"),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("department", "code")},
        ),
    ]
