# Generated by Django 5.1.4 on 2026-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رمز الإعداد"
                    ),
                ),
                ("value", models.TextField(verbose_name="قيمة الإعداد")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="وصف الإعداد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
            ],
            options={
                "verbose_name": "إعداد نظام (كود الأستاذ)",
                "verbose_name_plural": "إعدادات النظام وأكواد التحقق",
            },
        ),
    ]
