# Generated by Django 5.2.16 on 2026-07-14 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.PositiveIntegerField(verbose_name="معرف السجل")),
                (
                    "model_name",
                    models.CharField(
                        default="AttendanceRecord",
                        max_length=50,
                        verbose_name="اسم النموذج",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "إضافة"),
                            ("UPDATE", "تعديل"),
                            ("DELETE", "حذف"),
                        ],
                        max_length=10,
                        verbose_name="العملية",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="محتوى البيانات (JSON)")),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="تمت المزامنة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء في الطابور"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المزامنة للسحابة"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل المزامنة",
                "verbose_name_plural": "سجلات طابور المزامنة",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "qr_salt",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="ملح التشفير للـ QR"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت البدء"),
                ),
                ("end_time", models.DateTimeField(verbose_name="وقت الانتهاء")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "requires_wifi",
                    models.BooleanField(
                        default=False, verbose_name="تطلب التحقق من WiFi"
                    ),
                ),
                (
                    "requires_geofence",
                    models.BooleanField(
                        default=False, verbose_name="تطلب التحقق من الموقع الجغرافي"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُنشئ الجلسة",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.session",
                        verbose_name="الحصة/المحاضرة",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة تحضير",
                "verbose_name_plural": "جلسات التحضير",
                "unique_together": {("session", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "حاضر"),
                            ("ABSENT", "غائب"),
                            ("LATE", "متأخر"),
                            ("EXCUSED", "غائب بعذر"),
                        ],
                        default="ABSENT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("QR", "رمز QR الديناميكي"),
                            ("STATIC_QR", "بطاقة الطالب (QR ثابت)"),
                            ("WIFI", "شبكة WiFi"),
                            ("RFID", "بطاقة RFID / NFC"),
                            ("MANUAL", "يدوي (من المعلم)"),
                        ],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="طريقة التحضير",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="طابع وقت الحضور"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان الـ IP للجهاز"
                    ),
                ),
                (
                    "device_user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="معلومات المتصفح/الجهاز"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="ملاحظات / سبب التعديل اليدوي",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدله المستخدم",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="accounts.studentprofile",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "attendance_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.attendancesession",
                        verbose_name="جلسة التحضير",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حضور الطالب",
                "verbose_name_plural": "سجلات حضور الطلاب",
                "unique_together": {("student", "attendance_session")},
            },
        ),
    ]
