# Generated by Django 5.2.16 on 2026-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="allowed_ip_subnet",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="نطاق الـ IP المؤقت / Hotspot Subnet",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="allowed_wifi_ssid",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="اسم الـ WiFi المؤقت / Hotspot SSID",
            ),
        ),
    ]
