# Generated by Django 5.2.16 on 2026-09-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancesession_allowed_ip_subnet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="خط عرض المحاضرة",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="خط طول المحاضرة",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="quick_otp",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="رمز التحضير السريع (OTP)",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="radius_meters",
            field=models.PositiveIntegerField(
                default=50, verbose_name="نطاق السماح الجغرافي بالمتر"
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("QR", "رمز QR الديناميكي"),
                    ("STATIC_QR", "بطاقة الطالب (QR ثابت)"),
                    ("WIFI", "شبكة WiFi"),
                    ("RFID", "بطاقة RFID / NFC"),
                    ("MANUAL", "يدوي (من المعلم)"),
                    ("OTP", "رمز التحضير السريع (OTP)"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="طريقة التحضير",
            ),
        ),
    ]
