# Generated by Django 5.1.4 on 2026-09-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendancesession_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="lecture_type",
            field=models.CharField(
                blank=True, default="نظري", max_length=50, verbose_name="نوع المحاضرة"
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="topic",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="موضوع أو عنوان المحاضرة",
            ),
        ),
    ]
