# Generated by Django 5.1.4 on 2026-09-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendancesession_lecture_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="shift",
            field=models.CharField(
                choices=[("MORNING", "صباحي"), ("EVENING", "مسائي")],
                default="MORNING",
                max_length=10,
                verbose_name="نوع الدراسة (صباحي/مسائي)",
            ),
        ),
    ]
