# Generated by Django 5.1.4 on 2026-09-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendancesession_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="is_frozen_qr",
            field=models.BooleanField(
                default=False, verbose_name="تثبيت كود الـ QR (رمز ثابت)"
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("QR", "رمز QR الديناميكي"),
                    ("STATIC_QR", "بطاقة الطالب (QR ثابت)"),
                    ("WIFI", "شبكة WiFi"),
                    ("RFID", "بطاقة RFID / NFC"),
                    ("MANUAL", "يدوي (من المعلم)"),
                    ("OTP", "رمز التحضير السريع (OTP)"),
                    ("OFFLINE_MANUAL", "بدون إنترنت (تسجيل فوري)"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="طريقة التحضير",
            ),
        ),
    ]
