# Generated by Django 5.1.4 on 2026-10-02 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_teacherprofile_department"),
        ("attendance", "0006_attendancesession_is_frozen_qr_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineAttendanceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=150, verbose_name="اسم الطالب"),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="معرف الجهاز"
                    ),
                ),
                (
                    "queue_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="معرف طلب الجهاز"
                    ),
                ),
                (
                    "token_error",
                    models.CharField(max_length=255, verbose_name="سبب تعذر التحقق"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "بانتظار المراجعة"),
                            ("APPROVED", "تمت الموافقة"),
                            ("REJECTED", "مرفوض"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                        verbose_name="حالة المراجعة",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت استلام الخادم"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت المراجعة"
                    ),
                ),
                (
                    "attendance_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_submissions",
                        to="attendance.attendancesession",
                        verbose_name="جلسة التحضير",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_offline_attendance_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجع الطلب",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_attendance_submissions",
                        to="accounts.studentprofile",
                        verbose_name="ملف الطالب المعتمد",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب حضور غير متصل للمراجعة",
                "verbose_name_plural": "طلبات الحضور غير المتصلة للمراجعة",
                "ordering": ["received_at"],
            },
        ),
    ]
