# Generated by Django 5.2.16 on 2026-09-27 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ABSENCE", "إشعار غياب"),
                            ("LATE", "إشعار تأخر"),
                            ("SESSION_OPEN", "فتح جلسة تحضير"),
                            ("SESSION_CLOSE", "إغلاق جلسة تحضير"),
                            ("SYSTEM", "إشعار نظام"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="نص الإشعار")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القراءة"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    )
                ],
            },
        ),
    ]
